/** Hand-authored specs for flagship SKUs — images come from MD Photos via sync. */

import type { CatalogProduct, DentalSpecialtySlug } from '@/content/products.types';

type LegacySpec = Omit<CatalogProduct, 'image' | 'images' | 'imageAlt'> & {
  imageFile?: string;
};

export const LEGACY_PRODUCT_SPECS: LegacySpec[] = [
  {
    id: 'aditek-bracket-system',
    name: 'Aditek EasyClip+ Bracket System',
    brand: 'Aditek',
    brandSlug: 'aditek',
    specialty: 'Orthodontics',
    specialtySlug: 'ORTHODONTICS',
    subcategory: 'Brackets',
    keySpec: 'Self-ligating · 0.022"',
    imageFile: 'EasyClip+.JPG',
    description:
      'Low-profile self-ligating brackets engineered for efficient tooth movement and patient comfort in daily orthodontic practice.',
    specs: {
      'Slot size': '0.022"',
      'Base design': 'Mesh pad',
      Material: 'Stainless steel',
      'Bracket type': 'Self-ligating',
    },
    clinical: {
      indications: 'Fixed orthodontic treatment for malocclusion correction.',
      usage: 'Bond per manufacturer torque/angulation chart; verify full seating before light-cure.',
    },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['aditek-safira-mbt', 'aditek-bio-crystal'],
    publishedAt: '2026-02-10',
  },
  {
    id: 'bms-composite-kit',
    name: 'BMS FILLBEST Composite',
    brand: 'BMS',
    brandSlug: 'bms',
    specialty: 'Restorative',
    specialtySlug: 'RESTORATIVE',
    subcategory: 'Composites',
    keySpec: 'Shade-stable nanohybrid',
    imageFile: 'FILLBEST.JPG',
    description: 'Shade-stable composites for anterior and posterior restorations with polished aesthetics.',
    specs: { Type: 'Nanohybrid composite', Application: 'Direct restorations' },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['bms-cembest', 'bms-bleaching-kit'],
    publishedAt: '2026-01-18',
  },
  {
    id: 'bms-bonding-agent',
    name: 'BMS CEMBEST Cement',
    brand: 'BMS',
    brandSlug: 'bms',
    specialty: 'Restorative',
    specialtySlug: 'RESTORATIVE',
    subcategory: 'Cements',
    keySpec: 'Dual-cure cement',
    imageFile: 'CEMBEST.JPG',
    description: 'Dual-cure luting cement for restorative and prosthetic bonding protocols.',
    specs: { Type: 'Dual-cure cement' },
    certifications: ['CE'],
    relatedIds: ['bms-composite-kit'],
    publishedAt: '2026-02-14',
  },
  {
    id: 'heydent-zirconia-disc',
    name: 'Heydent Hey-TEC Universal',
    brand: 'Heydent',
    brandSlug: 'heydent',
    specialty: 'Restorative',
    specialtySlug: 'RESTORATIVE',
    subcategory: 'Composites',
    keySpec: 'Universal composite system',
    imageFile: 'Hey-TEC Universal.png',
    description: 'Universal composite system for direct aesthetic restorations with reliable polishability.',
    specs: { Type: 'Universal composite', Application: 'Anterior and posterior' },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['heydent-cem-veneer', 'heydent-bulk-ud'],
    publishedAt: '2026-01-22',
  },
  {
    id: 'heydent-polish-system',
    name: 'Heydent Flow V',
    brand: 'Heydent',
    brandSlug: 'heydent',
    specialty: 'Restorative',
    specialtySlug: 'RESTORATIVE',
    subcategory: 'Flowable composite',
    keySpec: 'Flowable composite',
    imageFile: 'Flow V.jpg',
    description: 'Flowable composite for cavity lining and small restorations.',
    specs: { Type: 'Flowable composite' },
    certifications: ['CE'],
    relatedIds: ['heydent-zirconia-disc'],
    publishedAt: '2026-02-16',
  },
  {
    id: 'sin-endo-file-set',
    name: 'SIN Endo File Set',
    brand: 'SIN',
    brandSlug: 'sin',
    specialty: 'Endodontics',
    specialtySlug: 'ENDODONTICS',
    subcategory: 'Rotary files',
    keySpec: 'NiTi rotary sequence',
    description: 'Color-coded nickel-titanium rotary files for predictable canal shaping.',
    specs: { Alloy: 'Nickel-titanium', Taper: '0.04–0.06' },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['profa-t-blue-30-4'],
    publishedAt: '2026-02-01',
  },
  {
    id: 'sin-sealer-kit',
    name: 'SIN Endo Sealer Kit',
    brand: 'SIN',
    brandSlug: 'sin',
    specialty: 'Endodontics',
    specialtySlug: 'ENDODONTICS',
    subcategory: 'Obturation',
    keySpec: 'Bioceramic sealer',
    description: 'Bioceramic root canal sealer for warm and cold obturation techniques.',
    specs: { Type: 'Bioceramic sealer' },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['sin-endo-file-set'],
    publishedAt: '2026-02-15',
  },
  {
    id: 'centrix-impression',
    name: 'Centrix NoMix Temporary Cement',
    brand: 'Centrix',
    brandSlug: 'centrix',
    specialty: 'Restorative',
    specialtySlug: 'RESTORATIVE',
    subcategory: 'Temporization',
    keySpec: 'No-mix automix',
    imageFile: 'NoMix.png',
    description: 'Temporary cement for crowns and bridges with simple automix delivery.',
    specs: { Type: 'Temporary cement', Delivery: 'Automix syringe' },
    certifications: ['CE', 'FDA'],
    relatedIds: ['centrix-temp-crown', 'centrix-fluorodose'],
    publishedAt: '2026-02-05',
  },
  {
    id: 'centrix-temp-crown',
    name: 'Centrix SuperCure Original',
    brand: 'Centrix',
    brandSlug: 'centrix',
    specialty: 'Restorative',
    specialtySlug: 'RESTORATIVE',
    subcategory: 'Core buildup',
    keySpec: 'Light-activated core material',
    imageFile: 'SuperCure Original.png',
    description: 'Light-activated core buildup material for durable foundation restorations.',
    specs: { Type: 'Core buildup', Cure: 'Light-activated' },
    certifications: ['CE', 'FDA'],
    relatedIds: ['centrix-impression'],
    publishedAt: '2026-02-18',
  },
  {
    id: 'profa-sterilization-pouch',
    name: 'PROFA T-Blue Rotary Files',
    brand: 'PROFA',
    brandSlug: 'profa',
    specialty: 'Endodontics',
    specialtySlug: 'ENDODONTICS',
    subcategory: 'Rotary files',
    keySpec: 'NiTi rotary · T-Blue',
    imageFile: 'T-blue 30.4.png',
    description: 'T-Blue nickel-titanium rotary files for efficient canal shaping.',
    specs: { System: 'T-Blue', Taper: '0.04' },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: ['profa-eli-gold', 'profa-k-files-25'],
    publishedAt: '2026-01-30',
  },
  {
    id: 'wbt-ortho-system',
    name: 'WBT Orthodontic System',
    brand: 'WBT',
    brandSlug: 'wbt',
    specialty: 'Orthodontics',
    specialtySlug: 'ORTHODONTICS',
    subcategory: 'Bracket kits',
    keySpec: 'Complete chairside kit',
    description: 'Complete bracket, archwire, and ligature kit for efficient orthodontic workflows.',
    specs: { 'Slot size': '0.022"' },
    certifications: ['CE'],
    relatedIds: ['aditek-bracket-system'],
    publishedAt: '2026-02-12',
  },
  {
    id: 'topglove-exam-gloves',
    name: 'TopGlove Exam Gloves',
    brand: 'TopGlove',
    brandSlug: 'topglove',
    specialty: 'Infection Control',
    specialtySlug: 'INFECTION_CONTROL',
    subcategory: 'Gloves',
    keySpec: 'Powder-free nitrile',
    description: 'Powder-free nitrile examination gloves for daily infection control.',
    specs: { Material: 'Nitrile', 'Powder-free': 'Yes' },
    certifications: ['CE', 'ISO 13485'],
    relatedIds: [],
    publishedAt: '2026-02-08',
  },
];

export const BRAND_DEFAULTS: Record<
  string,
  { brand: string; specialty: string; specialtySlug: DentalSpecialtySlug; subcategory: string }
> = {
  aditek: { brand: 'Aditek', specialty: 'Orthodontics', specialtySlug: 'ORTHODONTICS', subcategory: 'Orthodontics' },
  bms: { brand: 'BMS', specialty: 'Restorative', specialtySlug: 'RESTORATIVE', subcategory: 'Restorative' },
  centrix: { brand: 'Centrix', specialty: 'Preventive', specialtySlug: 'PREVENTIVE', subcategory: 'Preventive' },
  heydent: { brand: 'Heydent', specialty: 'Restorative', specialtySlug: 'RESTORATIVE', subcategory: 'Aesthetics' },
  profa: { brand: 'PROFA', specialty: 'Endodontics', specialtySlug: 'ENDODONTICS', subcategory: 'Endodontics' },
};
